### ISSUE TITLE
AWS Backend Lösung finden

### ISSUE THREAD

**Issue by LucWag92** [LucWag92/gamingDate#3]
- kostenlos
- AWS Lösung in der wir die Spring Boot Backend Seite laufen lassen können

**Comment by simonmtr** [comment]
Ich hab mal bisschen gegoogelt, schaut so aus als wuerde man bie AWS "EC2" fuer das hochladen von docker containern und microservices benutzen. Gibt auch ein kostenloses Kontingent, jedoch nur fuer 12 Monate. Denke aber auch dass es erstmal passen sollte, oder?

- AWS Seite: https://aws.amazon.com/de/ec2/
- Beispiel von AWS wie man deployed: https://www.youtube.com/watch?v=_ep_yKuDWkE&ab_channel=AmazonWebServices

Habe auch mal paar Youtube Videos geschaut, da gibts echt n paar die auch Spring benutzen und den Code auf AWS laden, also da gibts genug Infomaterial denk ich. Jedes mal benutzen die aber Docker, aber das sollte ja passen denk ich.
