### ISSUE TITLE
Diskussion über Branches

### ISSUE THREAD

**Issue by LucWag92** [LucWag92/gamingDate#5]
Wie entwickeln wir?

- Main Branch für Production only?
- Develop Branch für Dev Umgebung?
- Features werden in Dev Branch gemergt und dann in Prod gemergt?

**Comment by simonmtr** [comment]
Ja finde so wie dus gesagt hast passts gut 👍

**Comment by LucWag92** [comment]
Alles klar. Dann erstelle ich ein Anschluss Issue mit den Fragen, welche Bausteine wir in die CI/CD Pipeline bauen wollen
